apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ifwa9t3zb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ifwa9t3zb-python 
  name: ifwa9t3zb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ifwa9t3zb-python 
