apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ifwa9t3zb-python 
  janus-idp.io/tekton: ifwa9t3zb-python
  backstage.io/kubernetes-id: ifwa9t3zb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ifwa9t3zb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml